[build-system]
requires = ["setuptools>=75.2.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hue-entertainment-pykit"
version = "0.9.4"
authors = [
    {name = "Dominik Hrdas"}
]
description = "A comprehensive Python toolkit for Philips Hue Entertainment API"
readme = "README.md"
license = {file = "LICENSE.md"}
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Utilities"
]
requires-python = ">=3.10, <3.13"
dependencies = [
    "certifi==2025.11.12",
    "charset-normalizer==3.4.4",
    "click==8.3.1",
    "colorama==0.4.6",
    "idna==3.11",
    "ifaddr==0.2.0",
    "packaging==25.0",
    "pathspec==0.12.1",
    "platformdirs==4.5.1",
    "python-mbedtls==2.10.1",
    "requests==2.32.5",
    "typing_extensions==4.15.0",
    "urllib3==2.6.2",
    "zeroconf==0.148.0"
]
keywords = ["philips", "hue", "lights", "entertainment", "api"]

[project.urls]
Repository = "https://github.com/hrdasdominik/hue-entertainment-pykit"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

